### ISSUE TITLE
Object <-> Dynamo-Object

### ISSUE THREAD

**Issue by meaku** [epha/dynamo#4]
The current transformation takes care of the following transformation:

__Object__

```javascript
{ 
  UserId: "1",
  FileId: "xy",
  Name: 'bla',
  Size: 3,
  ItemsOnMyDesk: ['a', 'b'],
  testBoolean: true,
  Pens: {a: 'aa', b: 'bb'},
  Quantity: 12
}
```

becomes.... 

__DynamoDB Object__ 

```javascript
 {
  UserId: {S: '1'},
  FileId: {S: 'xy'},
  Name: {S: 'bla'},
  Size: {N: '3'},
  ItemsOnMyDesk: {
    L: [
      {S: 'a'},
      {S: 'b'}
    ]
  },
  Pens: {
    M: {
      a: {S: 'aa'},
      b: {S: 'bb'}
    }
  },
  testBoolean: {BOOL: true},
  Quantity: {N: '12'}
};
```

and the other way round. 

I'm not sure if we need a Schema or if we could just use type-checking. When using a schema we might have to add deeper nesting. At the moment lists and hashes are just prototyped becoming string values (there is still a TODO in transform.js). A Schema has the advantage of adding things like casting and sanitization.

**Comment by Jonas74** [comment]
An idea could be to define in the schema, besides casting, the encryption and encryption key.

**Comment by meaku** [comment]
I found another good looking dynamo library called [Dynamite](https://github.com/Medium/dynamite). They solve conversion using type checking: https://github.com/Medium/dynamite/blob/master/lib/typeUtil.js

**Comment by meaku** [comment]
I think the conversion from/to Objects <-> DynamoObjects should be enabled on default without using a schema. That's the way other libs are doing it.

There is a good lib we can use replacing the current transform implementation: https://github.com/kayomarz/dynamodb-data-types

**Comment by meaku** [comment]
The lib uses dynamo-data-types now. Transformation is enabled on default and can be enables/disabled by calling `db.useTransform(true/false)`.
